sudo: true
dist: trusty
language: c

compiler:
  - gcc-4.8
  - gcc-5
  - gcc-6
  - clang

install: .ci/install.sh
script: python3 arduinint test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - gcc-6
      - gcc-5
      - clang
      - make
      - valgrind
      - python3-pip
      - python3.5
